INSERT INTO propriedades (id, value)
VALUES ('VALOR_DIARIA_DIAS_UTEIS', '120.0'),
       ('VALOR_DIARIA_FERIADOS', '180.0'),
       ('VALOR_TAXA_ESTACIONAMENTO_DIAS_UTEIS', '15.0'),
       ('VALOR_TAXA_ESTACIONAMENTO_FERIADOS', '20.0'),
       ('HORARIO_MAXIMO_CHECKIN', '14:00:00'),
       ('HORARIO_MAXIMO_CHECKOUT', '12:00:00');